### PR TITLE
CORE-1251: Update Tezos Fee Estimation

### PR DESCRIPTION
**Pull request by EBGToo**
This DOES NOT fix the issue of computing the MAX amount to send.  This just improves the Tezos fee estimation by using all the individual operation estimates and the burn fee provided by Blockset.

### CODE REVIEW

**Comment by EBGToo** [comment]
The Core Demo App should show the correct fees for XTZ: transfers/delegation w/ or w/o Reveal and w/ or w/o Burn.

**Review by carlcherry — APPROVED** [review]
I was expecting to see the new values coming back from Blockset (fee_0, fee_1, etc) but don't see that anywhere.

**Comment by EBGToo** [comment]
> I was expecting to see the new values coming back from Blockset (fee_0, fee_1, etc) but don't see that anywhere.

The Blockset 'meta' JSON is parsed into {key, value} arrays and passed into the Tezos handler code.   In the handler code you have

```
static BRTezosOperationFeeBasis
wkWalletManagerRecoverOperationFeeBasis (const char *suffix, size_t count, const char **keys, const char **vals, bool *parseError) {
    assert (NULL == suffix || strlen(suffix) < 32);
    if (NULL == suffix) suffix = "";

    char key[128];

    bool hasKind = false;
    BRTezosOperationKind kind = wkWalletManagerRecoverOperationKind (cwmAppendSuffix (key, "kind", suffix), count, keys, vals, &hasKind);

    *parseError = false;
    int64_t fee         = cwmParseInt64 (cwmLookupAttributeValueForKey (cwmAppendSuffix (key, "fee",          suffix), count, keys, vals), parseError);
    int64_t burn        = cwmParseInt64 (cwmLookupAttributeValueForKey (cwmAppendSuffix (key, "burn",         suffix), count, keys, vals), parseError);
    int64_t gasUsed     = cwmParseInt64 (cwmLookupAttributeValueForKey (cwmAppendSuffix (key, "consumed_gas", suffix), count, keys, vals), parseError);
//    int64_t storageUsed = (int64_t) cwmParseUInt64 (cwmLookupAttributeValueForKey (cwmAppendSuffix (key, "storage_size", suffix), count, keys, vals), parseError);
    int64_t counter     = cwmParseInt64 (cwmLookupAttributeValueForKey (cwmAppendSuffix (key, "counter",      suffix), count, keys, vals), parseError);

    return tezosOperationFeeBasisCreate (kind,
                                         (BRTezosUnitMutez) fee,
                                         gasUsed,
                                         0,
                                         counter,
                                         (BRTezosUnitMutez) burn);
}
```

which handles all the Tezos meta data uniformly and which gets invoked with the two different suffixes:

```
    BRTezosOperationFeeBasis operationFeeBasis_0 = wkWalletManagerRecoverOperationFeeBasis ("_0", attributesCount, attributeKeys, attributeVals, &error_0);
    BRTezosOperationFeeBasis operationFeeBasis_1 = wkWalletManagerRecoverOperationFeeBasis ("_1", attributesCount, attributeKeys, attributeVals, &error_1);
```

**Review by ewerx — APPROVED** [review]

**Comment by EBGToo** [comment]
Addressed PR comments

**Pull request merged**
